FROM nvcr.io/nvidia/tensorflow:18.07-py3

WORKDIR /

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONIOENCODING=utf-8
ENV LANG=C.UTF-8

RUN pip install --upgrade pip

RUN curl -OL https://github.com/apiss2/dl_bash_for_docker/archive/master.zip
RUN unzip master.zip && rm master.zip && mv /dl_bash_for_docker-master/docker_build.sh / && rm -d /dl_bash_for_docker-master
RUN sh docker_build.sh

# install packages
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y curl unzip lv
RUN apt-get install -y python3-pip
RUN apt-get install -y git
RUN apt-get install -y wget
RUN apt-get install -y libsm6 libgl1 libxrender1
RUN pip uninstall tensorflow
RUN pip install tensorflow==1.8.0

# FCRN-DepthPrediction-vmd
RUN pip3 install python-dateutil
RUN pip3 install pytz
RUN pip3 install pyparsing
RUN pip3 install six
RUN pip3 install matplotlib
RUN pip3 install opencv-python==3.4.2.17
RUN pip3 install imageio

# 3d-pose-baseline-multi
RUN pip3 install h5py

# VMD-3d-pose-baseline-multi
RUN pip3 install PyQt5

# tf-pose-estimation
RUN apt-get install -y swig
RUN pip3 install Cython
RUN pip3 install argparse
RUN pip3 install dill
RUN pip3 install fire
RUN pip3 install matplotlib
RUN pip3 install numba
RUN pip3 install psutil
RUN pip3 install pycocotools
RUN pip3 install requests
RUN pip3 install scikit-image
RUN pip3 install scipy
RUN pip3 install slidingwindow
RUN pip3 install tqdm
RUN pip3 install git+https://github.com/ppwwyyxx/tensorpack.git

RUN unzip pose_est_mod.zip && rm pose_est_mod.zip
RUN cd /pose_est_mod/tf_pose_estimation/ \
 && cd tf_pose/pafprocess \
 && swig -python -c++ pafprocess.i \
 && python3 setup.py build_ext --inplace

CMD ["bash"]